spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:    #开发环境
    name: ldbspringcloud-config-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: ldbspringcloud-config-test
#请保存为UTF-8格式
